-- =============================================================================
-- nlsql-testbed: "Northpine Outfitters", an outdoor-gear retailer
--
-- A deliberately realistic Postgres schema for testing a zero-config NL->SQL
-- composer. Conventions are the common Rails/Django style (plural snake_case
-- tables, `id` primary keys, `<table>_id` foreign keys), but the schema is
-- seeded with the irregularities real databases have: missing FK constraints,
-- role-playing foreign keys, soft deletes, money in cents, snapshot tables,
-- enum types next to CHECK lists next to unconstrained text, and so on.
-- Each trap is listed in README.md with the eval cases that exercise it.
--
-- Load:  psql -d nlsql_test -f schema.sql && python3 seed.py | psql -d nlsql_test
-- =============================================================================

DROP SCHEMA IF EXISTS shop CASCADE;
CREATE SCHEMA shop;
SET search_path = shop;

-- ---------------------------------------------------------------------------
-- Enum types (introspected via pg_enum)
-- ---------------------------------------------------------------------------
CREATE TYPE customer_segment AS ENUM ('consumer', 'small_business', 'enterprise');
CREATE TYPE order_status     AS ENUM ('pending', 'paid', 'shipped', 'delivered', 'cancelled', 'refunded');
CREATE TYPE payment_method   AS ENUM ('card', 'paypal', 'gift_card', 'invoice');
CREATE TYPE ticket_priority  AS ENUM ('low', 'normal', 'high', 'urgent');

-- ---------------------------------------------------------------------------
-- Reference tables
-- ---------------------------------------------------------------------------
CREATE TABLE regions (
    id    smallint PRIMARY KEY,
    name  text    NOT NULL UNIQUE,
    code  char(1) NOT NULL UNIQUE
);
COMMENT ON TABLE regions IS 'Sales regions of the United States.';

CREATE TABLE warehouses (
    id         smallint PRIMARY KEY,
    name       text     NOT NULL UNIQUE,
    city       text     NOT NULL,
    state_code char(2)  NOT NULL,
    region_id  smallint NOT NULL REFERENCES regions (id),
    opened_on  date     NOT NULL
);
COMMENT ON TABLE warehouses IS 'Distribution centers that fulfill orders.';

CREATE TABLE categories (
    id        integer PRIMARY KEY,
    name      text    NOT NULL UNIQUE,
    parent_id integer REFERENCES categories (id)          -- self-reference: two-level hierarchy
);
COMMENT ON TABLE categories IS 'Product categories. Top-level categories have no parent; products belong to leaf categories.';

-- ---------------------------------------------------------------------------
-- Customers and addresses
-- ---------------------------------------------------------------------------
CREATE TABLE customers (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                   text             NOT NULL UNIQUE,
    first_name              text             NOT NULL,
    last_name               text             NOT NULL,
    company_name            text,                                         -- only business segments
    segment                 customer_segment NOT NULL,
    region_id               smallint         REFERENCES regions (id),
    referred_by_customer_id bigint           REFERENCES customers (id),   -- self-reference, role-named
    marketing_opt_in        boolean          NOT NULL DEFAULT false,
    loyalty_tier            text CHECK (loyalty_tier IN ('bronze', 'silver', 'gold', 'platinum')),
    created_at              timestamptz      NOT NULL,                    -- signup time (the only business timestamp)
    updated_at              timestamptz      NOT NULL,
    deleted_at              timestamptz                                   -- soft delete
);
COMMENT ON TABLE customers IS 'People and businesses that have an account.';
COMMENT ON COLUMN customers.created_at IS 'When the customer signed up.';
COMMENT ON COLUMN customers.deleted_at IS 'Set when the account is closed; closed accounts are kept for history.';

CREATE TABLE addresses (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  bigint  NOT NULL REFERENCES customers (id),
    label        text    NOT NULL CHECK (label IN ('home', 'work', 'other')),
    line1        text    NOT NULL,
    city         text    NOT NULL,
    state_code   char(2) NOT NULL,
    postal_code  text    NOT NULL,                     -- numeric-looking, not a measure
    country_code char(2) NOT NULL DEFAULT 'US',
    created_at   timestamptz NOT NULL
);

-- ---------------------------------------------------------------------------
-- Catalog
-- ---------------------------------------------------------------------------
CREATE TABLE products (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku              text     NOT NULL UNIQUE,
    name             text     NOT NULL,
    category_id      integer  NOT NULL REFERENCES categories (id),
    brand            text     NOT NULL,                -- low-cardinality text with no constraint
    list_price_cents integer  NOT NULL,                -- non-additive, money in cents
    unit_cost_cents  integer  NOT NULL,                -- non-additive, money in cents
    weight_grams     integer  NOT NULL,
    model_year       smallint NOT NULL,                -- numeric, never a measure
    is_active        boolean  NOT NULL DEFAULT true,
    launched_on      date     NOT NULL,
    discontinued_at  timestamptz,
    attributes       jsonb    NOT NULL DEFAULT '{}',   -- color, material, capacity (v2: JSON paths)
    created_at       timestamptz NOT NULL,
    updated_at       timestamptz NOT NULL
);
COMMENT ON TABLE products IS 'Items for sale.';

CREATE TABLE tags (
    id   integer PRIMARY KEY,
    name text NOT NULL UNIQUE
);

CREATE TABLE product_tags (                            -- junction table (many-to-many)
    product_id bigint  NOT NULL REFERENCES products (id),
    tag_id     integer NOT NULL REFERENCES tags (id),
    created_at timestamptz NOT NULL,
    PRIMARY KEY (product_id, tag_id)
);

-- ---------------------------------------------------------------------------
-- Orders
-- ---------------------------------------------------------------------------
CREATE TABLE orders (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number                text         NOT NULL UNIQUE,          -- 'NP-1000123'
    customer_id                 bigint       NOT NULL REFERENCES customers (id),
    billing_address_id          bigint       NOT NULL REFERENCES addresses (id),   -- role-playing FK
    shipping_address_id         bigint       NOT NULL REFERENCES addresses (id),   -- role-playing FK
    fulfilled_from_warehouse_id smallint     REFERENCES warehouses (id),           -- null until shipped
    status                      order_status NOT NULL,
    channel                     text         NOT NULL CHECK (channel IN ('web', 'mobile_app', 'marketplace', 'phone')),
    coupon_code                 text,
    placed_at                   timestamptz  NOT NULL,                  -- default business time
    shipped_at                  timestamptz,
    delivered_at                timestamptz,
    cancelled_at                timestamptz,
    subtotal_cents              integer      NOT NULL,                  -- sum of line totals
    discount_cents              integer      NOT NULL DEFAULT 0,        -- order-level coupon discount
    shipping_cents              integer      NOT NULL DEFAULT 0,
    tax_cents                   integer      NOT NULL DEFAULT 0,
    total_cents                 integer      NOT NULL,                  -- subtotal - discount + shipping + tax
    currency                    char(3)      NOT NULL DEFAULT 'USD',
    created_at                  timestamptz  NOT NULL,
    updated_at                  timestamptz  NOT NULL
);
COMMENT ON TABLE orders IS 'Customer orders. One row per order.';
COMMENT ON COLUMN orders.placed_at IS 'When the customer placed the order.';
COMMENT ON COLUMN orders.total_cents IS 'Amount charged to the customer, including tax and shipping.';

CREATE TABLE order_items (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         bigint       NOT NULL REFERENCES orders (id),
    product_id       bigint       NOT NULL REFERENCES products (id),
    quantity         integer      NOT NULL CHECK (quantity > 0),
    unit_price_cents integer      NOT NULL,                             -- non-additive
    discount_pct     numeric(5,2) NOT NULL DEFAULT 0,                   -- non-additive
    line_total_cents integer      NOT NULL                              -- additive
);
COMMENT ON TABLE order_items IS 'Lines within an order. One row per product per order.';

CREATE TABLE payments (                                -- second child of orders: chasm trap with order_items
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     bigint         NOT NULL REFERENCES orders (id),
    method       payment_method NOT NULL,
    amount_cents integer        NOT NULL,
    status       text           NOT NULL CHECK (status IN ('authorized', 'captured', 'failed', 'voided')),
    processed_at timestamptz    NOT NULL
);

CREATE TABLE refunds (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      bigint  NOT NULL REFERENCES orders (id),
    order_item_id bigint  REFERENCES order_items (id),   -- null = whole-order refund
    amount_cents  integer NOT NULL,
    reason        text    NOT NULL CHECK (reason IN ('damaged', 'wrong_item', 'late', 'changed_mind', 'other')),
    refunded_at   timestamptz NOT NULL
);
COMMENT ON TABLE refunds IS 'Money returned to customers. Partial refunds leave the order status unchanged.';

CREATE TABLE reviews (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id           bigint   NOT NULL REFERENCES products (id),
    customer_id          bigint   NOT NULL REFERENCES customers (id),
    rating               smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),   -- non-additive
    title                text     NOT NULL,
    body                 text     NOT NULL,                                  -- free text
    is_verified_purchase boolean  NOT NULL,
    created_at           timestamptz NOT NULL
);

-- ---------------------------------------------------------------------------
-- Inventory (snapshot table: semi-additive)
-- ---------------------------------------------------------------------------
CREATE TABLE inventory_snapshots (
    product_id     bigint   NOT NULL REFERENCES products (id),
    warehouse_id   smallint NOT NULL REFERENCES warehouses (id),
    snapshot_date  date     NOT NULL,
    on_hand_units  integer  NOT NULL,                  -- additive across products/warehouses, NOT across dates
    reserved_units integer  NOT NULL,
    PRIMARY KEY (product_id, warehouse_id, snapshot_date)
);
COMMENT ON TABLE inventory_snapshots IS 'Stock level per product and warehouse, taken on the first day of each month.';

-- ---------------------------------------------------------------------------
-- Support
-- ---------------------------------------------------------------------------
CREATE TABLE employees (
    id            integer PRIMARY KEY,
    full_name     text    NOT NULL,
    email         text    NOT NULL UNIQUE,
    team          text    NOT NULL CHECK (team IN ('support', 'sales', 'operations')),
    title         text    NOT NULL,
    manager_id    integer REFERENCES employees (id),   -- self-reference
    hired_on      date    NOT NULL,
    terminated_on date
);

CREATE TABLE support_tickets (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number           text            NOT NULL UNIQUE,
    customer_id             bigint          NOT NULL REFERENCES customers (id),
    order_id                bigint          REFERENCES orders (id),
    created_by_employee_id  integer         REFERENCES employees (id),   -- role-playing; null = customer self-service
    assigned_to_employee_id integer         REFERENCES employees (id),   -- role-playing; null = unassigned
    priority                ticket_priority NOT NULL,
    status                  text            NOT NULL CHECK (status IN ('open', 'pending', 'solved', 'closed')),
    channel                 text            NOT NULL CHECK (channel IN ('email', 'chat', 'phone', 'web_form')),
    subject                 text            NOT NULL,
    opened_at               timestamptz     NOT NULL,
    first_response_at       timestamptz,
    resolved_at             timestamptz,
    csat_score              smallint CHECK (csat_score BETWEEN 1 AND 5)  -- non-additive, sparse
);

-- ---------------------------------------------------------------------------
-- Analytics events: NO foreign key constraints, no comments (name-based inference only)
-- ---------------------------------------------------------------------------
CREATE TABLE web_sessions (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id        bigint,          -- -> customers.id, unconstrained; null = anonymous visitor
    started_at         timestamptz NOT NULL,
    ended_at           timestamptz NOT NULL,
    landing_page       text        NOT NULL,
    utm_source         text,
    device_type        text        NOT NULL,   -- 'desktop' | 'mobile' | 'tablet', unconstrained
    page_views         integer     NOT NULL,
    converted_order_id bigint                  -- -> orders.id, unconstrained, role-named
);

-- ---------------------------------------------------------------------------
-- Indexes on FKs and business timestamps
-- ---------------------------------------------------------------------------
CREATE INDEX ON customers (region_id);
CREATE INDEX ON addresses (customer_id);
CREATE INDEX ON products (category_id);
CREATE INDEX ON orders (customer_id);
CREATE INDEX ON orders (placed_at);
CREATE INDEX ON order_items (order_id);
CREATE INDEX ON order_items (product_id);
CREATE INDEX ON payments (order_id);
CREATE INDEX ON refunds (order_id);
CREATE INDEX ON reviews (product_id);
CREATE INDEX ON support_tickets (customer_id);
CREATE INDEX ON support_tickets (opened_at);
CREATE INDEX ON web_sessions (customer_id);
CREATE INDEX ON web_sessions (started_at);
